version: '3.8'
services:

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    working_dir: /app
    command: >
      mlflow server
      --backend-store-uri /app/mlruns
      --default-artifact-root /app/mlruns/artifacts
      --host 0.0.0.0
      --port 5001
    ports:
      - '5001:5001'
    volumes:
      - ./mlruns:/app/mlruns

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    working_dir: /app
    volumes:
      - ./mlruns:/app/mlruns
      - ./model/data:/app/model/data
      - ./model:/app/model
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - mlflow
    command: ["python", "-m", "model.movierec.train_model"]

  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '8000:8000'
    volumes:
      - ./mlruns:/app/mlruns
      - ./model:/app/model
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - mlflow

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - RECOMMENDER_URL=http://recommender:8000
    ports:
      - '4080:4080'
    depends_on:
      - recommender
