version: '3.8'
services:
  dvc-remote:
    image: minio/minio
    # configurazione DVC remote...

  mlflow:
    image: mlflow:latest
    command: mlflow server --backend-store-uri ./mlruns --default-artifact-root ./mlruns/artifacts --host 0.0.0.0 --port 5000
    ports:
      - '5000:5000'
    volumes:
      - ./mlruns:/mlruns

  recommender:
    build:
      context: .
      dockerfile: model/movierec/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./model/knn_model.pkl:/app/movierec/knn_model.pkl
      - ./model/data:/app/model/data

  web:
    build: .
    command: python main.py
    ports:
      - '4080:4080'
    depends_on:
      - recommender



prometheus:
  image: prom/prometheus:latest
  volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - "9090:9090"

grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  depends_on:
    - prometheus
