FROM python:3.9-slim

RUN pip install mlflow

EXPOSE 5001

CMD ["mlflow", "server", "--backend-store-uri", "./mlruns", "--default-artifact-root", "./mlruns/artifacts", "--host", "0.0.0.0", "--port", "5001"]
