version: '3.8'
services:

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    working_dir: /app
    command: >
      mlflow server
      --backend-store-uri /app/mlruns
      --default-artifact-root /app/mlruns/artifacts
      --host 0.0.0.0
      --port 5001
    ports:
      - '5001:5001'
    volumes:
      - ./mlruns:/app/mlruns   

  recommender:
    build:
      context: .
      dockerfile: Dockerfile       # il tuo Dockerfile del microservizio
    ports:
      - '8000:8000'
    volumes:
      - ./mlruns:/app/mlruns 
      - ./model/knn_model.pkl:/app/model/knn_model.pkl
      - ./model/data:/app/model/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001

  web:
    environment:
      - RECOMMENDER_URL=http://recommender:8000
    build:
      context: .
      dockerfile: Dockerfile.web   # il nuovo Dockerfile per il front-end
    ports:
      - '4080:4080'
    depends_on:
      - recommender
