stages:
  ingest:
    cmd: python scripts/data_ingestion.py
    deps:
      - model/data/movies.csv
      - model/data/ratings.csv
      - movie_data.py
    outs:
      - data/db.sqlite

  train:
    cmd: python train_model.py
    deps:
      - data/db.sqlite
      - model/src/load_data.py
      - model/src/data_preparation.py
      - model/movierec/recommender.py
    metrics:
      - mlruns/**/metrics.json

  serve:
    cmd: python main.py
    deps:
      - model/movierec/recommender_service.py
      - model/movierec/recommender.py