name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: DVC pull
        run: |
          pip install "dvc[s3]"
          dvc pull

      - name: Run tests
        run: pytest -q

      - name: Lint code
        run: flake8 .

      - name: Build Docker images
        run: docker-compose build --pull --parallel
